---
- name: Configure GFS2
  shell: "{{ item }}"
  loop:
    - " pcs cluster start --all"
    - " pcs property set stonith-enabled=false"
    - " pcs property set no-quorum-policy=freeze"
    - " pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
    - " pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
    - " pcs constraint order start dlm-clone then clvmd-clone"
    - " sleep 10"
    - " pvcreate /dev/sda"
    - " sleep 60"
    - " vgcreate -Ay -cy cluster_vg /dev/sda"
    - " lvcreate -L900M -n cluster_lv cluster_vg"
    - " mkfs.gfs2 -O -j3 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv"
    - ' pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2"  fstype="gfs2" "options=noatime" op monitor interval=10s  on-fail=ignore clone interleave=true'
    - " pcs constraint order start clvmd-clone then clusterfs-clone"
    - " pcs constraint colocation add clusterfs-clone with clvmd-clone"