---
- name: Ensure hostname set
  hosts: all
  become: true
  tasks:
    - ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Configure hosts file
      copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes

- name: Install and configure load balancer servers
  hosts: load_balancer_servers
  become: true
  roles:
    - load_balancer

- name: Install and configure mysql server
  hosts: db_server
  become: true
  roles:
    - mysql

- name: Install and configure iscsi-target
  become: true
  hosts: iscsi
  roles:
    - iscsi-target

- name: Install and configure iscsi-clients
  hosts: web_servers
  become: true
  roles:
    - pacemaker
    - iscsi-client

- name: Configure GFS2
  become: true
  hosts: web-0
  roles:
    - config-gfs2

- name: Install and configure web servers
  become: true
  hosts: web_servers
  roles:
    - web

- name: Install WordPress and tune cluster
  become: true
  hosts: web-0
  roles:
    - wp
    - tune-cluster

- name: Install and configure Filebeat
  become: true
  hosts: web
  roles:
    - filebeat

- name: Install and configure Kafka
  become: true
  hosts: kafka
  roles:
    - kafka

- name: Install and configure ELK
  become: true
  hosts: elk
  roles:
    - elk