---
- name: Restart keepalived
  become: true
  service:
    name: keepalived
    state: restarted

- name: Restart nginx
  become: true  
  service:
    name: nginx
    state: restarted

# - name: Reload nginx
#   systemd:
#     name: nginx
#     state: reloaded

# - name: Setenforce
#   command: setenforce 0